# Array(数组)
* rank: 维数

In [1]:
import numpy as np     # 导入库

手动创建数组

In [2]:
a = np.array([1,2,3])    # 创建数组

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape     # 数组大小，只有第一位有数字，表示这是一个一维数组，但是无法判断是行向量还是列向量。

(3,)

In [6]:
a = a.reshape((1,-1))    # 重塑矩阵，可以明确是行向量还是列向量，其中1表示1行，-1表示占位符，原来数组有3个元素，所以这里-1表示3

In [7]:
a.shape

(1, 3)

In [8]:
a = np.array([1,2,3,4,5,6])

In [9]:
a.shape    # 一维数组，有6个元素

(6,)

In [10]:
a = a.reshape((2,-1))    # 在这里，因为有6个元素，2行，所以-1占位符表示3

In [11]:
a.shape

(2, 3)

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a = a.reshape((-1,2))

In [14]:
a.shape

(3, 2)

In [15]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a[2,0]

5

In [17]:
a[2,0] = 55     # 将原本第三行第一列的5换成55

In [18]:
a

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

zeros: 用来创建元素全为0的数组

In [19]:
a = np.zeros((3,3))      # 创建一个3*3的元素全是0的二维矩阵

In [20]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

ones: 用来创建元素全是1的数组

In [21]:
a = np.ones((2,3))

In [22]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

full: 可以实现上面的ones和zeros

In [23]:
a = np.full((3,3), 0)      # 创建一个3*3的元素全是0的二维数组

D:\Dev\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((3, 3), 0) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [24]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [25]:
a = np.full((2,3), 1)

D:\Dev\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((2, 3), 1) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [26]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

eye: 用于创建单位矩阵，也就是从左上角到右下角全是1的矩阵，其余元素全是0

In [27]:
a = np.eye(3)    # 创建一个3*3的单位矩阵

In [28]:
a

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

random.random: 用来创建随机数组，元素的值都在0-1之间

In [29]:
a = np.random.random((3,4))

In [30]:
a

array([[ 0.29690476,  0.0351068 ,  0.71882284,  0.42428351],
       [ 0.49810766,  0.73570413,  0.25068501,  0.27180163],
       [ 0.25599994,  0.81167766,  0.70356101,  0.00607248]])

# indexing

In [31]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [32]:
a[-2:, 1:3]       # -2:表示从倒数第二行到最后，1:3表示从第二列到第三列

array([[ 6,  7],
       [10, 11]])

In [33]:
a[-2:][1:3]

array([[ 9, 10, 11, 12]])

In [34]:
a[1,-2]

7

In [35]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
a.shape

(3, 4)

In [37]:
b = a[-2:, 1:3]

In [38]:
b.shape

(2, 2)

In [39]:
b = a[2, 1:3]

In [40]:
b

array([10, 11])

In [41]:
b.shape     # 所以说即使a是二维数组，产生的也有有可能是一维数组

(2,)

In [42]:
b = a[1,2]

In [43]:
b

7

In [44]:
b.shape

()

In [45]:
b = a[2, 1:3]

In [46]:
b

array([10, 11])

In [47]:
b.shape

(2,)

In [48]:
b = a[2:3, 1:3]

In [49]:
b

array([[10, 11]])

In [50]:
b.shape      # 注意如果在取索引的时候，有任意一个是整数，不是切片的话，那么shape会对应维数减一

(1, 2)

In [51]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
a[np.arange(3), 1] += 10

In [53]:
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [54]:
np.arange(3)    # 用来产生指定范围的数组

array([0, 1, 2])

In [55]:
np.arange(3,7)

array([3, 4, 5, 6])

In [56]:
a[np.arange(3), [1,1,1]] += 10

In [57]:
a

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

In [58]:
 a[[0,1,2], [1,1,1]] += 10

In [59]:
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

In [60]:
result = a>10

In [61]:
result

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]], dtype=bool)

In [62]:
a[result]

array([32, 36, 40, 11, 12])

In [63]:
a[a>10]

array([32, 36, 40, 11, 12])

# 元素的数据类型

In [63]:
a = np.array([1,2])    # 元素均为整数，识别为int

In [64]:
a.dtype

dtype('int32')

In [65]:
a = np.array([1.1,2.2])      # 元素均为小数，识别为float

In [66]:
a.dtype

dtype('float64')

In [67]:
a = np.array([1,2.2])      # 元素有小数也有整数，识别为float

In [68]:
a.dtype

dtype('float64')

In [69]:
a = np.array([1.1,2.6])

In [70]:
a = np.array([1.1,2.6], dtype=np.int64)     # 本来元素是小数，设置类型为int，会自动把小数点后面的数字去掉

In [71]:
a

array([1, 2], dtype=int64)

In [72]:
a = np.array([1.1,2.6])

In [73]:
b = np.array(a, dtype=np.int64)      # b的元素取自a元素的整数部分

In [74]:
b

array([1, 2], dtype=int64)

# 数学运算与常用函数

In [75]:
a = np.array([[1,2],
            [3,4]])

In [76]:
b = np.array([[5,6],
             [6,5]])

In [77]:
a + b

array([[6, 8],
       [9, 9]])

In [78]:
np.add(a,b)

array([[6, 8],
       [9, 9]])

In [79]:
a - b

array([[-4, -4],
       [-3, -1]])

In [80]:
np.subtract(a,b)

array([[-4, -4],
       [-3, -1]])

In [81]:
a * b

array([[ 5, 12],
       [18, 20]])

In [82]:
np.multiply(a,b)

array([[ 5, 12],
       [18, 20]])

In [83]:
a / b

array([[ 0.2       ,  0.33333333],
       [ 0.5       ,  0.8       ]])

In [84]:
np.divide(a,b)

array([[ 0.2       ,  0.33333333],
       [ 0.5       ,  0.8       ]])

In [85]:
np.sqrt(a)           # 上面这些操作是将具有相同大小的数组的元素进行操作，并不是矩阵之间的操作

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

a.dot(b): 矩阵乘法

In [86]:
a

array([[1, 2],
       [3, 4]])

In [87]:
b = np.array([[1,2,3],
             [4,5,6]])

In [88]:
a.dot(b)        # 矩阵a和矩阵b相乘

array([[ 9, 12, 15],
       [19, 26, 33]])

In [89]:
np.dot(a,b)     # 和上面的效果是一样的，a的列数和b的行数是一致的

array([[ 9, 12, 15],
       [19, 26, 33]])

## 常用函数

sum

In [90]:
a

array([[1, 2],
       [3, 4]])

In [91]:
np.sum(a)    # 对数组a的所有元素进行求和

10

In [92]:
np.sum(a,axis=0)        # 对数组a的每一列进行求和操作

array([4, 6])

In [93]:
np.sum(a,axis=1)     # 对数组的每一行进行求和操作

array([3, 7])

mean

In [94]:
np.mean(a)       # a中所有元素求和的平均值

2.5

In [95]:
np.mean(a,axis=0)     # 对数组a的每一列求和的平均值

array([ 2.,  3.])

In [96]:
np.mean(a,axis=1)      # 数组a的每一列的平均值

array([ 1.5,  3.5])

uniform

In [98]:
np.random.uniform(3,4)      # 生成指定范围内的随机小数

3.5576025608378723

In [100]:
np.random.uniform(1,100)

83.7570173313416

tile: 用于将一个数组作为元素重复指定的次数。

In [102]:
a

array([[1, 2],
       [3, 4]])

In [103]:
np.tile(a,(1,2))     # 将a作为一个元素，变成1行2列的新数组

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [104]:
np.tile(a,(2,1))      # 将a作为元素，在行上重复2次，在列上重复1次

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [106]:
np.tile(a,(2,3))     # a作为元素，在行上重复2次，在列上重复3次

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

argsort: 用于将数组中的元素排序

In [107]:
a = np.array([[3,6,4,11],
             [5,10,1,3]])

In [108]:
a.argsort()     # 默认情况下对每一行的元素进行从小到大的排序，返回的是元素的下标

array([[0, 2, 1, 3],
       [2, 3, 0, 1]], dtype=int64)

In [109]:
a.argsort(axis=0)     # 对每一列的元素排序

array([[0, 0, 1, 1],
       [1, 1, 0, 0]], dtype=int64)

矩阵转置

In [110]:
a

array([[ 3,  6,  4, 11],
       [ 5, 10,  1,  3]])

In [111]:
a.T

array([[ 3,  5],
       [ 6, 10],
       [ 4,  1],
       [11,  3]])

In [112]:
np.transpose(a)    # 和上面一样的效果

array([[ 3,  5],
       [ 6, 10],
       [ 4,  1],
       [11,  3]])

# 广播

In [113]:
a = np.array([[1,2,3],
             [2,3,4],
             [12,31,22],
             [2,2,2]])                  # 二维的4*3的数组

In [114]:
b = np.array([1,2,3])

需求：将a的每一行和b相加

In [115]:
# 如果数组a比较大的话，使用这种方法会非常低效，因为python中for循环计算比较慢
for i in range(4):     # a一共是4行
    a[i,:] += b         # 将a的每一行和b相加

In [116]:
a                 # 得到的正确结果

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [13, 33, 25],
       [ 3,  4,  5]])

In [117]:
# 数组比较大的时候可以私用这种方法
a + np.tile(b, (4,1))

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])

In [118]:
# 在numpy中使用广播会更加简单,下面就是广播
# 也就是说我们可以将不同维度的数组进行相加，numpy会自动将数组转换为相同维度，广播会在缺失维度和数值为1的维度上进行，这就是numpy广播特性
a + b

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])